### ISSUE TITLE
cmd: ":write_output {directory};:quit" doesn't quit until another key or key combo is hit

### ISSUE THREAD

**Issue by AndydeCleyre** [Canop/broot#1006]
I'm using this verb:

```yml
{
  key: alt-enter
  invocation: cd
  cmd: ":write_output {directory};:quit"
}
```

and launching with `broot --verb-output /tmp/somefile`

When invoked either by the `alt-enter` or by typing `cd`, the file is written to, but broot doesn't quit. If I hit `alt-enter` again, the file gets a second line identical to the first, and broot quits. If I instead hit an arrow key, broot also quits.

I'm reproducing this on Arch Linux with all releases from 1.45.1, but not seeing it in 1.45.0.
