### ISSUE TITLE
verb with focus_staging_area_no_open remains active after invoking

### ISSUE THREAD

**Issue by AndydeCleyre** [Canop/broot#1007]
Hello!

It looks like there's been a change between v1.45.0 and v1.45.1 affecting usage of the verb `rm` below. 

**Before:** After using the verb with a staging area open and not focused, the filter/action line would be cleared. 

**After:** After using the verb with a staging area open and not focused, the invocation command string remains on the filter/action line. At least the first time.

I discovered this when I intended to trash some files, then open one. Instead, I trashed the one I intended to open as well. It was recovered from the trash, nothing was really lost.

**Verb definitions:**

```yaml
{
  invocation: trashcli {file}
  external: trash {file}
  leave_broot: false
}
{
  invocation: rm
  cmd: ":focus_staging_area_no_open;:trashcli {file}"
}
```

The external `trash` command is from [andreafrancia/trash-cli](https://github.com/andreafrancia/trash-cli).

It looks like the only commit between those versions was: https://github.com/Canop/broot/commit/0942e8fa48d730dde14d44884e4f3942680e69a4
