### ISSUE TITLE
Swap shortcuts for enter and alt-enter

### ISSUE THREAD

**Issue by balta2ar** [Canop/broot#224]
I'd like `Enter` to cd and close broot, and `alt-enter` to open directory. Basically, I want to swap default behavior of `enter` and `alt-enter`. I've tried the following configuration, but it didn't seem to change behavior:
```toml
[[verbs]]
key = "enter"
execution = ":cd"

[[verbs]]
key = "alt-enter"
execution = ":open_stay"
```
