### ISSUE TITLE
Way to add input edition shortcuts

### ISSUE THREAD

**Issue by Canop** [Canop/broot#235]
This comes from issue #234 

> I miss the following shortcuts a lot: alt-backspace to delete previous word, alt-d delete following word, alt-b/alt-f go to previous/next word, alt-e go to the end of the word, ctrl-a/ctrl-e go to beginning/end of the line.

**Comment by Canop** [comment]
Done.

You may now add this kind of shortcuts:

```toml
[[verbs]]
key = "alt-b"
execution = ":input_go_word_left"

[[verbs]]
key = "alt-f"
execution = ":input_go_word_right"

[[verbs]]
key = "alt-l"
execution = ":input_del_word_left"

[[verbs]]
key = "alt-r"
execution = ":input_del_word_right"
```
