### ISSUE TITLE
Allow case-sensitive keys in config

### ISSUE THREAD

**Issue by D1mon** [Canop/broot#445]
```
[[verbs]]
execution = ":stage"
key = "m"

[[verbs]]
execution = ":unstage"
key = "M"
```
Now in the application, this is a similar command: "m" == "M":
m    :stage
m    :unstage

**Comment by Canop** [comment]
The problem is rather with the unclear syntax broot uses for key shortcuts.

You have to be explicit with the pressed keys:

```TOML
[[verbs]]
execution = ":unstage"
key = "shift-M"
```
