### ISSUE TITLE
View in subprocess on windowless server

### ISSUE THREAD

**Issue by tombh** [Canop/broot#547]
Of course this trick is really useful:
```toml
[[verbs]]
name = "view"
key = "enter"
invocation = "view"
execution = "xdg-open {file}"
```

But it doesn't open in a subprocess, so there doesn't seem to be a way to easily return to my previous broot state? I don't know how that could actually work, could broot be backgrounded then foregrounded when the subprocess exits?
