### ISSUE TITLE
How to use imports to inherit settings, then override values (like default_flags)?

### ISSUE THREAD

**Issue by AndydeCleyre** [Canop/broot#579]
I'm creating an issue for this question, as requested at https://github.com/Canop/broot/issues/152#issuecomment-1185176610.

---

I have a general/common broot config file (`conf.hjson`), and then some smaller configs that I'd like to apply on top during some invocations, adding and/or replacing values from `conf.hjson`.

For example, sometimes I want to use broot to select a folder to `cd` into (in the shell), and in that case I only want to see folders, not files.

`conf.hjson` includes `default_flags: igs`. I then have `select-folder.hjson`:

```yaml
{

  imports: [

    conf.hjson

  ]

  default_flags: igf

  verbs: [

    {
      apply_to: "directory"
      internal: ":print_path"
      key: "enter"
      leave_broot: true
    }

    {
      apply_to: "file"
      cmd: ":focus;:print_path"
      key: "enter"
      leave_broot: true
    }

  ]

}

```

I invoke broot with this config in Zsh by hitting `alt`+`down`, and the following Zsh loaded:

```zsh
.zle_redraw-prompt () {
  # Credit: romkatv/z4h
  emulate -L zsh
  for 1 ( chpwd $chpwd_functions precmd $precmd_functions ) {
    if (( $+functions[$1] ))  $1 &>/dev/null
  }
  zle .reset-prompt
  zle -R
}

.zle_cd-broot () {
  echoti rmkx
  cd "$(broot --color yes --conf ~/.config/broot/select-folder.hjson)"
  .zle_redraw-prompt
}
zle -N .zle_cd-broot
bindkey '^[[1;3B' .zle_cd-broot  # alt+down
```

I am surprised by the result: files as well as folders are shown, not only folders.

How can I get the value of `default_flags` defined in `select-folder.hjson` to apply, when using imports to combine config files?
