### ISSUE TITLE
Safer alternative to default rm -rf command 

### ISSUE THREAD

**Issue by kvnvallis** [Canop/broot#651]
The default behavior of typing `:rm` or ` rm` followed by Enter is concerning. If you have the wrong thing highlighted, like a folder full of important files, it will run `rm -rf` on that folder and delete everything in it without prompting you. 

I changed my rm command to `rm -i`. May I suggest either not having a default rm command (like how the touch verb is commented out for creating new files) or choosing something safer? The standard `rm` shell command without any options would be fine. Being momentarily confused about not being able to delete a directory is better than accidentally deleting a whole tree. 

This behavior was found in arch linux with broot version 1.19.0-1

**Comment by Stargateur** [comment]
`rm -r` could be a thing I guess, but no `rm -i` would be just useless.

**Comment by Canop** [comment]
You don't have to close this, even if I don't answer. I don't think the answer is in changing the command itself but I prefer the issue to stay visible so that people give their opinion. Maybe the solution would be in some kind of warning dialog on first execution, I don't know.

**Comment by Canop** [comment]
Related: there's now a `:trash` internal, which may be used like this:

    {
        invocation: "rm"
        internal: "trash"
        leave_broot: false
    }

**Comment by kvnvallis** [comment]
I just tried it on windows. It works great!

**Comment by AndydeCleyre** [comment]
The trash feature AFAIK understand is not enabled by default at build time, so for example the official Arch Linux package will fail to run a verb configured to use it.

So on systems with the trash feature I use

```yml
{
  invocation: rm
  cmd: ":focus_staging_area_no_open;:trash {file}"
}
```

On systems without the trash feature but with trash-cli installed:

```yml
{
  invocation: trashcli {file}
  external: trash {file}
  leave_broot: false
}
{
  invocation: rm
  cmd: ":focus_staging_area_no_open;:trashcli {file}"
}
```

And on systems with neither I'll need to figure out a third configuration. I'm not sure if there is a problem trying to define a new `rm` that uses the internal `rm`. I think I used to do that and it worked. 🤷🏼 

I don't love this setup and am not recommending it. I'm sharing in case it makes problems/solutions clearer.
