### ISSUE TITLE
Verb precedence

### ISSUE THREAD

**Issue by 9999years** [Canop/broot#763]
In my `conf.toml`, I have an `edit` verb defined to open files in Neovim:

```toml
[[verbs]]
key = "enter"
invocation = "edit"
shortcut = "e"
apply_to = "file"
external = "nvim {file}"
leave_broot = false
```

In my [`broot.nvim`](https://github.com/9999years/broot.nvim) plugin, I load up another configuration file as well to override the `edit` verb to edit the file in the current Neovim session instead:

```toml
[[verbs]]
key = "enter"
invocation = "edit"
shortcut = "e"
apply_to = "file"
external = "broot.nvim edit +{line} {file}"
from_shell = true
```

(Other editor integrations use `:print_path` instead, but the concept is the same.)

Unfortunately, this doesn't work; the first matching verb is used, so the `broot.nvim` definition never gets triggered.

I'd really like the _last_ matching verb to be used, or to otherwise have some notion of "more important" and "less important" verbs.
