### ISSUE TITLE
Integration with `direnv`/`.envrc`

### ISSUE THREAD

**Issue by musjj** [Canop/broot#765]
When you try to `:edit` a file, the `.envrc` associated with the project will not be triggered before opening the file. An integration with `direnv` to automatically deal with `.envrc` files would be immensely useful.

**Comment by musjj** [comment]
It looks like that you can do this instead:

```toml
invocation = "edit"
shortcut = "e"
external = "direnv exec {directory} $EDITOR {file}"
set_working_dir = true;
leave_broot = false;
```

I think this is good enough for me!
