### ISSUE TITLE
MacOS 10.14 No application knows how to open - panic

### ISSUE THREAD

**Issue by costincaraivan** [Canop/broot#91]
**Describe the bug**
broot crashes on MacOS/zsh if $EDITOR is undefined and <Enter> is used to open a file.

**To Reproduce**
1. brew install broot
2. allow it to setup .zshrc
3. launch br
4. filter .gradle files (no $EDITOR defined)
5. 

```
gradle                                                                                                    h:n   gi:athread

'<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:1165:5

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

Open Error : "command \'open\' did not execute successfully; exit code: 1\ncommand stderr:\nNo application knows how to open [...]build.gradle."
```

**Expected behavior**
broot either opens the `build.gradle` file with $EDITOR, or if $EDITOR is undefined, asks the user to set it. broot doesn't crash/panic.

**Configuration (please complete the following information):**
- broot 0.10.3 installed with brew
 - OS: MacOS
 - Version 10.14
 - zsh 5.3 (x86_64-apple-darwin18.0)

**Additional information**
Broot also messes up iTerm2 at the end, using the mouse wheel to scroll prints characters instead of scrolling. I have to `reset` to get the terminal back to normal.

**Comment by JAStanton** [comment]
Digging around I found the config file (`~/Library/Preferences/org.dystroy.broot/conf.toml` or in broot type `?` and scroll down using arrow keys and it lists the config file location)

Inside there I found it mentions $EDITOR:

```toml
# If $EDITOR isn't set on your computer, you should either set it
#  or just replace it with your editor of choice in the 'execution'
#  pattern.
# Example:
#  execution = "/usr/bin/nvim {file}"
[[verbs]]
invocation = "edit"
key = "F2"
shortcut = "e"
execution = "$EDITOR {file}"
```
